import type { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  schema: '../backend/src/graphql/snapshots/schema.graphql',
  documents: ['src/graphql/**/*.graphql'],
  generates: {
    'src/generated/graphql.ts': {
      plugins: [
        {
          add: {
            content: [
              '// THIS FILE IS AUTO-GENERATED by graphql-code-generator.',
              '// DO NOT edit it manually. Run `npm run codegen` to regenerate.',
              '// Source schema: backend/src/graphql/snapshots/schema.graphql',
              '// Source documents: src/graphql/**/*.graphql',
              '',
            ].join('\n'),
            placement: 'prepend',
          },
        },
        'typescript',
        'typescript-operations',
        {
          'typescript-react-query': {
            fetcher: {
              func: '../graphql/client#fetcher',
            },
            // @tanstack/react-query v5 compatibility
            reactQueryVersion: 5,
            addInfiniteQuery: false,
            exposeQueryKeys: true,
            exposeFetcher: true,
          },
        },
      ],
      config: {
        // Map GraphQL scalars to TypeScript primitives
        scalars: {
          ID: 'string',
          Float: 'number',
          Int: 'number',
          Boolean: 'boolean',
          String: 'string',
        },
        // Generate strict non-nullable types
        avoidOptionals: false,
        maybeValue: 'T | null | undefined',
        // Naming conventions
        enumsAsTypes: true,
        skipTypename: false,
        // ReactQuery-specific
        dedupeFragments: true,
      },
    },
  },
};


export default config;
